install:
  - choco install gitversion.portable -pre -y
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

branches:
  only:
    - master
  
before_build: 
  - nuget restore
  - ps: gitversion /l console /output buildserver
  - ps: .\Update-VsixVersion.ps1 -Version $env:GitVersion_AssemblySemVer

build_script:
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
- ps: Vsix-PushArtifacts | Vsix-PublishToGallery