// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gardiner.XsltTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS2019.db207d71-2564-4b88-947b-678ac3b282c8";
        public const string Name = "XsltCop";
        public const string Description = @"XSLT Editor enhancements and static analysis tool. 

Navigation, refactoring and checking for common mistakes in XSLT files.

Static analysis runs on Build, and lists any rule violations in the Error List window";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "David Gardiner";
        public const string Tags = "";
    }
}
