// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gardiner.XsltTools
{
    static class Vsix
    {
        public const string Id = "Gardiner.XsltTools.David Gardiner.9f30a511-362f-4ebe-bc2d-4b987c1b9a96";
        public const string Name = "XsltCop";
        public const string Description = @"XSLT Editor enhancements and static analysis tool. 

Navigation, refactoring and checking for common mistakes in XSLT files.

Static analysis runs on Build, and lists any rule violations in the Error List window";
        public const string Language = "en-US";
        public const string Version = "1.1.1";
        public const string Author = "David Gardiner";
        public const string Tags = "xslt, static analysis, fxcop";
    }
}
