// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gardiner.XsltTools
{
    static class Vsix
    {
        public const string Id = "Gardiner.XsltTools.David Gardiner.9f30a511-362f-4ebe-bc2d-4b987c1b9a96";
        public const string Name = "XsltTools";
        public const string Description = "Various tools to enhance editing and checking XSLT files";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "David Gardiner";
        public const string Tags = "";
    }
}
