# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: packages
        # An explicit key for restoring and saving the cache
        key: nuget-packages-${{ hashFiles('**packages.config') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: nuget-packages-
        
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      #with:
        # Folder location of where vswhere.exe is located if a self-hosted agent
        #vswhere-path: # optional
        # Version of Visual Studio to search; defaults to latest if not specified
        #vs-version: # optional
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1
      with:
        # NuGet version to install. Can be `latest`, `preview`, a concrete version like `5.3.1`, or a semver range specifier like `5.x`.
        nuget-version: latest

    - name: NuGet Restore
      run: nuget restore
      
    # Runs a single command using the runners shell
    - name: Build
      run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
